### ISSUE TITLE
Ability to generate status codes from user code

### ISSUE THREAD

**Issue by moleike** [http4s/http4s-grpc#135]
As it stands now, we have no way to propagate/generate gRPC statuses from a server application. Whenever the application errors, the server encodes it into an `UNKNOWN` status. The codes are documented here: https://github.com/grpc/grpc.io/blob/main/content/en/docs/guides/status-codes.md

**Comment by Jasper-M** [comment]
I think adding a `StatusRuntimeException` like in grpc-java might make sense. And seems easy to implement as well.

**Comment by hamnis** [comment]
this sounds reasonable, would you be willing to add a PR for that?

**Comment by amoreno-netquest** [comment]
sure thing, I'll give it a stab soon.

**Comment by moleike** [comment]
Sure thing, I'll give it a stab soon.
